--- 
title: "Statistical Methods for Environmental Mixtures"
author: "Andrea Bellavia"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: andreabellavia/mixtures
description: "Humans are simultaneously exposed to a large number of environmental hazards. To allow a more accurate identification of the risks associated with environmental exposures and developing more targeted public health interventions, it is crucial that population-based studies account for the complexity of such exposures as environmental mixtures. This poses several analytic challenges and often requires the use of extensions of standard regression approaches or more flexible techinques for high-dimensional data. This document presents an extended version of the class material that was used in an introductory two-weeks course on statistical approaches for environmental mixtures. The main challanges and limitations of standard regression techniques are outlined, and recent methodological developments are introduced in a rigorous yet non-theoretical way. The course was designed for students and postdocs in environmental health with basic preliminary knoweldge on linear and logistic regression models. Sources and code examples to conduct a thorough analysis in R are also included." 
---

# Preface {-}

This document contains an extended version of the material for the winter class in "Statistical methods for Environmental Mixtures", which I taught at the Harvard T.H. Chan School of Public Health between 2018 and 2020. The course was designed as a 2-weeks intensive introductory class, which made it realistically impossible to cover all topics and methodologies related to the continuously expanding field of statistical approaches for high-dimensional exposures, and their application in exposome research. As such, the goal of this document is not to comprehensibly summarize the existing literature, but only to present in teaching format the selected topics covered in the course. Credits should also go to Dr. Paige Williams and Prof. Brent Coull who give guest lectures during the course on principal components analysis and Bayesian Kernel Machine Regression: the material related to these topics that is here discussed is largely taken from their material. 

The statistical software R was used for the practical sessions in the class. Despite some introduction to the specific packages and examples are here provided, the reader should refer to online documentations, provided from links throughout the document, for detailed descriptions of the software.

# About the Author {-}
Andrea Bellavia, PhD  
Lead Biostatistician / Research Scientist  
[TIMI study group](https://timi.org/)  
Brigham and Womens Hospital / Harvard Medical School  

Web: [andreabellavia.github.io](https://andreabellavia.github.io/)  
Twitter: [andreabellavia](https://twitter.com/andreabellavia?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor)


